version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/server.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build: .
    image: kevincaster0720843306/node-app
    # ports:
    #   - "3000:3000"
    environment:
      - PORT=3000
    restart: always
    links:
      - mongo
      - redis
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=kevin
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis
volumes:
  mongo-db:
